# Generated by Django 4.2.7 on 2023-12-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='summary',
            new_name='surname',
        ),
    ]
