# Generated by Django 4.2 on 2023-12-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='detail_image',
            field=models.ImageField(default='S', help_text='this is for dont resizing the image in product detail', upload_to='media/games/detail_image/%y/%m/%d/', verbose_name='most discounted image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='most_discounted_image',
            field=models.ImageField(blank=True, help_text='this is for dont resizing the image in site if this game is most discounted', null=True, upload_to='media/games/most_discount_image/%y/%m/%d/', verbose_name='most discounted image'),
        ),
        migrations.AlterField(
            model_name='game',
            name='most_played_image',
            field=models.ImageField(blank=True, help_text='this is for dont resizing the image in site if this game is most played', null=True, upload_to='media/games/most_played_image/%y/%m/%d/', verbose_name='most played image'),
        ),
    ]
