# Generated by Django 4.2 on 2023-12-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_tag_category_created_date_gamegener_created_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameTags',
            new_name='GameTag',
        ),
    ]
