# Generated by Django 4.2 on 2023-12-01 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_rename_gametags_gametag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gamegener',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='gametag',
            unique_together=set(),
        ),
    ]
