# Generated by Django 4.2.7 on 2023-12-08 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_game_unique_fields_alter_game_is_trending_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameGener',
            new_name='GameGenre',
        ),
        migrations.RenameModel(
            old_name='Gener',
            new_name='Genre',
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'genre', 'verbose_name_plural': 'genres'},
        ),
        migrations.RenameField(
            model_name='gamegenre',
            old_name='gener',
            new_name='genre',
        ),
        migrations.AlterUniqueTogether(
            name='gamegenre',
            unique_together={('game', 'genre')},
        ),
    ]
