# Generated by Django 4.2.7 on 2023-12-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_rename_gamegener_gamegenre_rename_gener_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='descriptions',
            new_name='description',
        ),
    ]
